// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/27/2025, 2:18:55 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/weblib/Desktop/health/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/weblib/Desktop/health/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/weblib/Desktop/health/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/weblib/Desktop/health/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/weblib/Desktop/health/plugins/**/*.{js,ts,mjs}","/Users/weblib/Desktop/health/composables/**/*.{js,ts,mjs}","/Users/weblib/Desktop/health/utils/**/*.{js,ts,mjs}","/Users/weblib/Desktop/health/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/weblib/Desktop/health/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/weblib/Desktop/health/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/weblib/Desktop/health/app.config.{js,ts,mjs}","/Users/weblib/Desktop/health/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;